[MM-873]: Added server testcases for api/event.go
mattermost/mattermost-plugin-mscalendar pull request #421
Opened 2024-10-21 07:25 UTC by Kshitij-Katiyar

### Summary
Added server testcases for api/event.go

2024-10-21 13:01 UTC, wiggin77 approved these changes
LGTM :+1:

2024-10-22 03:29 UTC, raghavaggarwal2308 requested changes

2024-10-22 03:29 UTC, raghavaggarwal2308 commented on calendar/api/events_test.go
> +				mockStore.EXPECT().LoadUser(MockUserID).Return(nil, store.ErrNotFound)
Can we add .Times() in all these mocks

2024-10-22 03:29 UTC, raghavaggarwal2308 commented on calendar/api/events_test.go
> +				mockEvent := &remote.Event{
We should create a test util for this as it is being created multiple times

2024-10-22 03:29 UTC, raghavaggarwal2308 commented on calendar/api/events_test.go
> +				mockEvent := &remote.Event{
If not possible for the whole object we can divide it into chunks

2024-10-22 03:29 UTC, raghavaggarwal2308 commented on calendar/api/events_test.go
> +				validJSON := fmt.Sprintf(`{
We have created a constant similar to this. Cant we use that here? Maybe we can create a util which accepts a param channeID

2024-10-22 03:29 UTC, raghavaggarwal2308 commented on calendar/api/test_utils.go
> +					"all_day": false,
Same for this

2024-12-04 14:08 UTC, raghavaggarwal2308 approved these changes

2024-12-04 14:08 UTC, merged