Add server testcase for engine/user.go
mattermost/mattermost-plugin-mscalendar pull request #427
Opened 2024-10-28 09:27 UTC by Kshitij-Katiyar

### Summary
Add server testcase for engine/user.go

2024-10-28 13:45 UTC, wiggin77 approved these changes
LGTM :+1:

2024-12-05 07:34 UTC, raghavaggarwal2308 requested changes

2024-12-05 07:34 UTC, raghavaggarwal2308 commented on calendar/engine/user_test.go
> +			user: &User{
We can use the existing util for getting this

2024-12-05 07:34 UTC, raghavaggarwal2308 commented on calendar/engine/user_test.go
> +			user: &User{
We just have to modify that a little

2024-12-05 07:34 UTC, raghavaggarwal2308 commented on calendar/engine/user_test.go
> +				mockStore.EXPECT().LoadSubscription(MockEventSubscriptionID).Return(nil, nil)
Add .Times() everywhere

2024-12-05 07:34 UTC, raghavaggarwal2308 commented on calendar/engine/user_test.go
> +			mattermostUserID: "mockMMUserID",
Can use one of the existing constants

2024-12-05 07:34 UTC, raghavaggarwal2308 commented on calendar/engine/user_test.go
> +				mockUser.User = &store.User{Settings: store.Settings{GetConfirmation: false}, Remote: &remote.User{ID: "testRemoteID"}}
Can use one of the existing constant for ID

2024-12-16 12:53 UTC, raghavaggarwal2308 approved these changes

2024-12-16 12:53 UTC, merged